# Generated by Django 3.2.14 on 2022-07-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelapp', '0003_auto_20220707_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Petrol_model',
        ),
    ]
